version: "3.9"

services:
  rest:
    container_name: example_rest_golang
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      REST_HOST: rest
      DB_HOST: database
      DB_PORT: 5432
    networks:
      example_network:
    depends_on:
      database:
        condition: service_healthy


  rest_dev:
    container_name: example_rest_dev_golang
    build:
      context: .
      target: rest_watch
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      REST_HOST: rest_dev
      DB_HOST: database
      DB_PORT: 5432
    networks:
      example_network:
    depends_on:
      database:
        condition: service_healthy
    links:
      - database
    volumes:
      - ./:/app


  database:
    image: postgres:latest
    container_name: example_db_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d example_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - example_volume:/var/lib/postgresql/data
    networks:
      example_network:

  migration:
    container_name: example_migration
    build:
      context: .
      target: "migration"
    env_file:
      - .env
    environment:
      DB_HOST: database
      DB_PORT: 5432
    depends_on:
      database:
        condition: service_healthy
    networks:
      example_network:
    volumes:
      - ./:/app

volumes:
  example_volume:

networks:
  example_network: